<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GoDeploy')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/vendor/bootstrap/dist/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/vendor/bootstrap/dist/css/bootstrap.min.css') ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/vendor/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/vendor/jquery/dist/jquery.min.js')
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('image/godeploy.png') ?>" alt="GoDeploy" id="nav-logo" /></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <ul>
                    <li>&copy; <?php echo date('Y') ?> by James Titcumb</li>
                <?php if($this->zfcUserIdentity()): ?>
                    <li>Logged in as <strong><?php echo $this->zfcUserIdentity()->getDisplayname(); ?></strong></li>
                    <li><a href="<?php echo $this->url('zfcuser/changepassword'); ?>">Change Password</a></li>
                    <li><a href="<?php echo $this->url('zfcuser/logout') ?>">Logout</a></li>
                <?php endif; ?>
                </ul>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
