
<div class="content">
	<div class="padding_20"></div>

	<h1><?php echo $this->project->getName(); ?></h1>
	<div class="padding_15"></div>

	<div id="form"><div class="wrapper w_ededed"><div class="content">
		<div class="padding_15"></div>

		<h2><?php __("Start Deployment"); ?></h2>

	<?php if ($this->form->isErrors()) : ?>
		<div id="errors"><div class="content">
			<?php __("There was a problem with your submission. Please check the fields highlighted below."); ?>
		</div></div>
		<div class="padding_15"></div>
	<?php endif; ?>
		<?php echo $this->form; ?>

	</div></div></div>
</div>