
<div class="content">
<div class="padding_20"></div>
<h1><?php echo $this->project->getName(); ?> - <?php _e("Deployment"); ?></h1>
<div class="padding_15"></div>

<div class="wrapper w_ededed"><div class="content">
	<div class="padding_15"></div>
	<h2><?php _e("Summary"); ?></h2>
	<div id="form">
		<form id="deploySummary" enctype="application/x-www-form-urlencoded" action="" method="post">
			<fieldset>
				<ol>
					<li>
						<label><?php _e("Deploy to"); ?></label>
						<span class="value"><?php echo $this->deployment->getServer()->getDisplayName(); ?></span>
					</li>
					<li>
						<label><?php _e("Repository URL"); ?></label>
						<span class="value"><?php echo $this->project->getRepositoryUrl(); ?></span>
					</li>
				<?php if($this->deployment->getFromRevision() != ""): ?>
					<li>
						<label><?php _e("From"); ?></label>
						<span class="value"><span class="monospace"><?php echo $this->deployment->getFromRevision(); ?></span></span>
					</li>
				<?php endif; ?>
					<li>
						<label><?php _e("To"); ?></label>
						<span class="value"><span class="monospace"><?php echo $this->deployment->getToRevision(); ?></span></span>
					</li>
					<li>
						<label><?php _e("Comment"); ?></label>
						<span class="value">
						<?php if($this->deployment->getComment() != ""): ?>
							<?php echo $this->escape($this->deployment->getComment()); ?>
						<?php else: ?>
							<small><em>No comment for this deployment</em></small>
						<?php endif; ?>
						</span>
					</li>
					<li>
						<label><?php _e("Status"); ?></label>
						<span class="value" id="deployment_status">
							<img src="/images/icons/<?php echo $this->deployment->getDeploymentStatus()->getImageName(); ?>" alt="icon" />
							<?php echo $this->deployment->getDeploymentStatus()->getName(); ?>
						</span>
					</li>
					<li class="submit">
				<?php
					switch($this->mode)
					{
						case 'PREVIEW':
				?>
						<input type="image" name="btn_run" id="btn_run" src="/images/buttons/small/deploy.png">
						<input type="image" name="btn_back" id="btn_back" src="/images/buttons/small/go-back.png">
				<?php
						break;
						case 'RESULT':
				?>
						<input type="image" name="btn_history" id="btn_history" src="/images/buttons/small/go-to-deployment-history.png">
				<?php
						break;
					}
				?>
					</li>
				</ol>
			</fieldset>
		</form>
	</div>
</div></div>

<div class="padding_20"></div>

<div class="wrapper w_ededed"><div class="content">
	<div class="padding_15"></div>
	<h2><?php _e("Deployment Details"); ?></h2>

	<?php if(is_array($this->file_list) && count($this->file_list) > 0): ?>
	<table>
		<thead>
			<tr>
				<th><?php _e("File"); ?></th>
				<th><?php _e("Action"); ?></th>
				<th><?php _e("Status"); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->file_list as $file): ?>
			<tr>
				<td><?php echo preg_replace('/(!CFG!\d+!)(.*)/', '$2 <strong>(Configuration File)</strong>', $file->getDetails()); ?></td>
				<td class="nowrap"><?php echo $file->getDeploymentFileAction()->getName(); ?></td>
				<td id="file_<?php echo $file->getId(); ?>_status" class="nowrap">
					<img src="/images/icons/<?php echo $file->getDeploymentFileStatus()->getImageName(); ?>" alt="icon" />
					<?php echo $file->getDeploymentFileStatus()->getName(); ?>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<?php else: ?>
	<h3><?php _e("There are no files to deploy."); ?></h3>
	<?php endif; ?>
</div></div>

<div class="padding_15"></div>
</div>

<?php if($this->mode == 'RUN'): ?>
<script type="text/javascript">
//<![CDATA[

$(document).observe("dom:loaded", bootstrapDeployment);
//]]>
</script>
<?php elseif($this->mode == 'RUNNING'): ?>
<script type="text/javascript">
//<![CDATA[

$(document).observe("dom:loaded", continueDeployment);
//]]>
</script>
<?php endif; ?>
