<h2>Summary</h2>
<ul>
	<li>
		<label>Deploy to<label>
		<span class="value"><?php echo $this->deployment->getServersId(); ?></span>
	</li>
	<li>
		<label>Repository URL<label>
		<span class="value"><?php echo $this->project->getRepositoryUrl(); ?></span>
	</li>
	<?php if($this->deployment->getFromRevision() != ""): ?>
	<li>
		<label>From<label>
		<span class="value"><?php echo $this->deployment->getFromRevision(); ?></span>
	</li>
	<?php endif; ?>
	<li>
		<label>To<label>
		<span class="value"><?php echo $this->deployment->getToRevision(); ?></span>
	</li>
	<li>
		<label>Status<label>
		<span class="value"><?php echo $this->deployment->getDeploymentStatusesId(); ?></span>
	</li>
</ul>

<h2>Deployment Details</h2>

<?php if(is_array($this->file_list) && count($this->file_list) > 0): ?>
<table>
	<thead>
		<tr>
			<th>File</th>
			<th>Action</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->file_list as $file): ?>
		<tr>
			<td><?php echo $file->getDetails(); ?></td>
			<td><?php echo $file->getDeploymentFileAction()->getName(); ?></td>
			<td><?php echo $file->getDeploymentFileStatus()->getName(); ?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php else: ?>
<h3>Looks like there are no files to deploy...?!</h3>
<?php endif; ?>
