
<h1><?php echo $project->getDisplayName(); ?> : View Deployment History</h1>

<table class="table table-striped table-hover table-bordered" >
    <thead>
        <tr>
            <th>Date</th>
            <th>Revision</th>
            <th>Comment</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($deployments as $deployment): ?>
        <tr>
            <td><?php echo $deployment->getDateAdded('d/m/Y H:i'); ?></td>
            <td><?php echo $deployment->getRevision(); ?></td>
            <td><?php echo $deployment->getComment(); ?></td>
            <td><?php echo $deployment->getStatus(); ?></td>
            <td><a href="<?php echo $this->url('show-deployment', ['deployment' => $deployment->getId()]); ?>">View</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>