
<h1><a href="<?php echo $this->url('project-settings', ['project' => $project->getName()]); ?>"><?php echo $project->getDisplayName(); ?></a> : View Deployment History</h1>

<table class="table table-striped table-hover" >
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th>Date</th>
            <th>From</th>
            <th>To</th>
            <th>Who</th>
            <th>Comment</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($deployments as $deployment): ?>
        <tr>
            <td><?php echo $deployment->getId(); ?></td>
            <td><?php echo $deployment->getDateAdded('d/m/Y H:i'); ?></td>
            <td title="<?php echo $deployment->getPreviousRevision(); ?>">
                <code><?php echo substr($deployment->getPreviousRevision(), 0, 8); ?></code>
            </td>
            <td title="<?php echo $deployment->hasResolvedRevision() ? $deployment->getResolvedRevision() : $deployment->getRevision(); ?>">
                <code><?php echo $deployment->hasResolvedRevision() ? substr($deployment->getResolvedRevision(), 0, 8) : $deployment->getRevision(); ?></code>
            </td>
            <td><?php echo $users[$deployment->getUserId()]->getDisplayName(); ?></td>
            <td><?php echo $deployment->getComment(); ?></td>
            <td><?php echo $deployment->getStatus(); ?></td>
            <td><a href="<?php echo $this->url('show-deployment', ['deployment' => $deployment->getId()]); ?>">View</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>