language: php

php:
  - 5.5
  - 5.6

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
  - php -m | grep ssh2
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors --verbose

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
