
<div class="padding_15"></div>
<div class="wrapper w_ededed">
	<div class="padding_15"></div>

	<div class="column c_123"><div class="content">

		<h3>Easy Code Deployment</h3>
		<p class="last">
			GoDeploy is an installable tool that enables you to deploy changes from a Git repository to an FTP or SFTP server. It works with any Git server (not just GitHub!).
			GoDeploy is Open Source software which means you can help us make the software better. <a href="<?php echo $this->baseUrl(); ?>/contribute" title="Contribute">Visit the Contribute page to find out more &raquo;</a>
		</p>

	</div></div>
	<div id="twitter" class="column c_4"><div class="border_left_narrow"><div class="content">
		<div class="padding_5"></div>

		<a href="http://www.twitter.com/ChiefWigs1982" rel="external"><img src="<?php echo $this->baseUrl(); ?>/images/pages/index/follow-us-on-twitter.png" alt="Follow us on twitter" /></a>
		<div class="padding_5"></div>

	</div></div></div>
	<div class="clear"></div>

</div>
<div class="padding_30"></div>
<div id="intro">
	<div class="column c_12"><div class="content">

		<h1>Easy Code Deployment</h1>
		<div class="padding_15"></div>
		<ul class="bullets large">
			<li class="item_1">Set up your Git connection and FTP/SSH details</li>
			<li class="item_2">Review changes to be uploaded</li>
			<li class="item_3">Click a button to deploy changes!</li>
		</ul>
		<div class="padding_5"></div>
		<div class="cta"><a href="<?php echo $this->baseUrl(); ?>/login" title="Login"><img src="<?php echo $this->baseUrl(); ?>/images/buttons/lets-get-started.png" alt="Let's get started &raquo;" /></a></div>
		<div class="padding_15"></div>

	</div></div>
	<div class="column c_34"><div class="content">

		<img src="<?php echo $this->baseUrl(); ?>/images/pages/index/screenshots.gif" alt="Screenshot" />

	</div></div>
</div>
<div class="clear"></div>
