
<h1>Create Deployment : <?php echo $project->getName(); ?></h1>

<?php

echo $this->form()->openTag($form);

$latestRevisionLink = '<a href="javascript:;" onclick="$(\'#deploy-revision\').val(\'origin/master\');">Use latest on master</a>';

echo $this->btsFormRow($form->get('revision'), $latestRevisionLink);
echo $this->btsFormRow($form->get('comment'));

echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();

?>
