
<?php $this->headScript()->appendFile('/js/create-deployment.js'); ?>

<h1>Create Deployment : <?php echo $project->getDisplayName(); ?></h1>

<?php

echo $this->form()->openTag($form);

$latestRevisionLink = '<a href="javascript:;" id="get-latest-revision" data-project="' . $project->getName() . '">Get latest revision on master</a>';

echo $this->btsFormRow($form->get('revision'), $latestRevisionLink);
echo $this->btsFormRow($form->get('comment'));

echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();

?>
