
<div class="column c_12"><div class="content"><div class="content">
	<div class="padding_20"></div>
	<div class="padding_15"></div>
	<h3>Easy Code Deployment</h3>
	<p class="last">
		GoDeploy is an installable tool that enables you to deploy changes from a Git repository to an FTP or SFTP server. It works with any Git server (not just GitHub!).
		GoDeploy is Open Source software which means you can help us make the software better. <a href="<?php echo $this->baseUrl(); ?>/contribute" title="Contribute">Visit the Contribute page to find out more &raquo;</a>
	</p>
</div></div></div>
<div class="column c_34"><div class="content">
	<div class="padding_20"></div>

	<div class="wrapper w_ededed">
		<div class="content">
			<div class="padding_15"></div>
			<h3 class="last">Login to GoDeploy</h3>
			<div class="padding_10"></div>

		<?php if ($this->form->isErrors()) { ?>
			<div id="errors"><div class="content">
				<?php if ($this->unknownCredentials) { ?>
					<?php echo reset($this->form->getMessages()); ?>
				<?php } else { ?>
					There was a problem with your submission. Please check the fields highlighted below.
				<?php } ?>
			</div></div>
			<div class="padding_15"></div>
		<?php } ?>

			<div id="form">
				<?php echo $this->form; ?>
			</div>

		</div>
	</div>

</div></div>
<div class="clear"></div>
