
<div class="column c_12"><div class="content">

	<div class="padding_20"></div>

	<h1><?php __("Easy Code Deployment"); ?></h1>
	<div class="padding_15"></div>
	<p><?php __("GoDeploy is an installable tool that enables you to deploy changes from a Git repository to an FTP or SFTP server. It works with any Git server (not just GitHub!). GoDeploy is Open Source software which means you can help us make the software better."); ?></p>
	<p class="last"><a href="<?php echo $this->baseUrl(); ?>/contribute" title="Contribute"><?php __("Visit the Contribute page to find out more"); ?> &raquo;</a></p>

</div></div>
<div class="column c_34">
	<div class="padding_20"></div>

	<div class="wrapper w_ededed">
		<div class="content">
			<div class="padding_15"></div>
			<h3 class="last"><?php __("Login to GoDeploy"); ?></h3>
			<div class="padding_10"></div>

		<?php if ($this->form->isErrors()) : ?>
			<div id="errors"><div class="content">
				<?php if ($this->unknownCredentials) : ?>
					<?php $msgs = $this->form->getMessages(); echo reset($msgs); ?>
				<?php else : ?>
					<?php __("There was a problem with your submission. Please check the fields highlighted below."); ?>
				<?php endif; ?>
			</div></div>
			<div class="padding_15"></div>
		<?php endif; ?>

			<div id="form">
				<?php echo $this->form; ?>
			</div>

		</div>
	</div>

</div>
<div class="clear"></div>
<div class="padding_15"></div>
