<h1>Projects</h1>

<?php if (is_array($projects) && count($projects) > 0): ?>
<table class="table table-hover" id="projects-list">
    <tbody>
    <?php foreach ($projects as $project): /* @var $project \Deploy\Entity\Project */ ?>
        <tr class="<?php echo $project->isStale ? 'stale' : ''; ?>">
            <td class="project-name"><?php echo $project->getDisplayName(); ?></td>
            <td class="nowrap">
                @ <code><?php echo substr($project->currentCommit, 0, 8); ?></code>
            <?php if ($project->isStale): ?>
                (latest is <code><?php echo substr($project->latestCommit, 0, 8); ?></code>)
            <?php endif; ?>
            </td>
            <td><a href="<?php echo $this->url('project-settings', ['project' => $project->getName()]); ?>">Settings</a></td>
            <td><a href="<?php echo $this->url('view-history', ['project' => $project->getName()]); ?>">View history</a></td>
            <td><a href="<?php echo $this->url('create-deployment', ['project' => $project->getName()]); ?>" class="btn btn-success">GoDeploy!</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<p class="bg-danger" style="padding: 15px;"><strong>Warning -</strong> there are no projects defined...</p>
<?php endif; ?>
