<h1>Projects</h1>

<?php if (is_array($projects) && count($projects) > 0): ?>
<table class="table table-striped table-hover table-bordered" id="projects-list">
    <tbody>
    <?php foreach ($projects as $project): /* @var $project \Deploy\Entity\Project */ ?>
        <tr>
            <td class="project-name"><?php echo $project->getDisplayName(); ?></td>
            <td title="not implemented yet...">View history</td>
            <td><a href="<?php echo $this->url('create-deployment', ['project' => $project->getName()]); ?>" class="btn btn-success">GoDeploy!</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<p class="bg-danger" style="padding: 15px;"><strong>Warning -</strong> there are no projects defined...</p>
<?php endif; ?>
