
<h1>
    <a href="<?php echo $this->url('project-settings', ['project' => $project->getName()]); ?>"><?php echo $project->getDisplayName(); ?></a>
    :
    <a href="<?php echo $this->url('project-settings', ['project' => $project->getName(), 'action' => 'view-tasks']); ?>">Tasks</a>
    :
    <?php echo $breadcrumb; ?>
</h1>

<?php
$form->prepare();
echo $this->form()->openTag($form);

echo $this->btsFormRow($form->get('command'));
echo $this->btsFormRow($form->get('directory'));
echo $this->btsFormRow($form->get('onlyOnTargets'));

echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();
?>
