
<h1><a href="<?php echo $this->url('project-settings', ['project' => $project->getName()]); ?>"><?php echo $project->getDisplayName(); ?></a> : Tasks</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Order</th>
            <th>Command</th>
            <th>Directory</th>
            <th>Only on targets</th>
            <th>Not on targets</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th colspan="5">&nbsp;</th>
            <th><a href="<?php echo $this->url('project-settings', ['action' => 'edit-task', 'project' => $project->getName()]); ?>" class="btn btn-success btn-xs">Add task</a></td>
        </tr>
    </tfoot>
    <tbody>
    <?php
    end($tasks);
    $lastTaskIndex = key($tasks);
    ?>
    <?php foreach ($tasks as $taskIndex => $task): ?>
        <tr>
            <td><?php echo $task->getOrder(); ?></td>
            <td><?php echo $task->getCommand(); ?></td>
            <td><?php echo $task->getDirectory() ?: '<em>Use default path</em>'; ?></td>
            <td><?php echo $task->getOnlyOnTargets(', ') ?: '<em>No restrictions</em>'; ?></td>
            <td><?php echo $task->getNotOnTargets(', ') ?: '<em>No restrictions</em>'; ?></td>
            <td>
                <a href="<?php echo $this->url('project-settings', ['action' => 'edit-task', 'project' => $project->getName(), 'objectId' => $task->getId()]); ?>" class="btn btn-default btn-xs">Edit</a>
                <a href="<?php echo $this->url('project-settings', ['action' => 'delete-task', 'project' => $project->getName(), 'objectId' => $task->getId()]); ?>" class="btn btn-danger btn-xs">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
