
<div class="content">
	<div class="padding_20"></div>

	<h1><?php echo $this->project->getName(); ?> &raquo; <?php _e("Deployment History"); ?></h1>
	<div class="padding_15"></div>

	<div class="wrapper w_ededed"><div class="content">
		<div class="padding_15"></div>

<?php if (is_array($this->deployments) && count($this->deployments) > 0): ?>

	<h2><?php _e("Deployment history"); ?></h2>

	<?php
		$count = count($this->deployments);
		if($count == "1"):
	?>

		<p><?php _e("There is 1 deployment shown."); ?></p>

	<?php else: ?>

		<p>
			<?php
				echo _r("There are");
				echo " " . $count . " ";
				echo _r(" of ");
				echo " " . $this->total_deployments . " ";
				echo _r(" deployments shown, with the most recent at the top.");
			?>
		</p>

	<?php endif; ?>

		<div id="feed_icons">
			<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $this->project->getSlug(); ?>/history/rss">
				<img src="/images/icons/feed/rss.png" title="<?php _e("RSS Feed"); ?>" alt="RSS" />
			</a>
			<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $this->project->getSlug(); ?>/history/json">
				<img src="/images/icons/feed/json.png" title="<?php _e("JSON Feed"); ?>" alt="JSON" />
			</a>
			<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $this->project->getSlug(); ?>/history/csv">
				<img src="/images/icons/feed/csv.png" title="<?php _e("CSV Feed"); ?>" alt="CSV" />
			</a>
		</div>
		<p><?php _e("The feeds are also available in RSS, JSON or CSV. Click the icon on the right for a feed of the deployment history..."); ?></p>

	<?php if($this->last_page > 1): ?>
		<div class="sep"></div>

		<div id="page_nav">
			<p><?php _e("Pages:"); ?></p>
			<ul>
			<?php for($i = 1; $i <= $this->last_page; $i++): ?>
				<li>
					<?php if($i == $this->current_page): ?>
						<?php echo $i; ?>
					<?php else: ?>
						<a href="history?page=<?php echo $i; ?>"><?php echo $i; ?></a>
					<?php endif; ?>
				</li>
			<?php endfor; ?>
			</ul>
		</div>
	<?php endif; ?>
		<table>
			<thead>
				<tr>
					<th><?php _e("Date"); ?>/<?php _e("Time"); ?></th>
					<th><?php _e("Server"); ?></th>
					<th><?php _e("From"); ?></th>
					<th><?php _e("To"); ?></th>
					<th><?php _e("Comment"); ?></th>
					<th><?php _e("By"); ?></th>
					<th><?php _e("Status"); ?></th>
					<th class="empty" colspan="2">&nbsp;</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($this->deployments as $deployment) : ?>
				<tr>
					<td class="nowrap">
						<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $this->project->getSlug(); ?>/deploy/result/<?php echo $deployment->getId(); ?>">
							<?php echo $deployment->getWhen("d/m/Y H:i:s"); ?>
						</a>
					</td>
					<td title="<?php echo $deployment->getServer()->getDisplayName(); ?>" class="nowrap"><?php echo $deployment->getServer()->getName(); ?></td>
					<td title="<?php echo $deployment->getFromRevision(); ?>"><?php echo $deployment->getFromRevision() ? ('<span class="monospace">' . substr($deployment->getFromRevision(), 0, 7) . '</span') : _r("None"); ?></span></td>
					<td title="<?php echo $deployment->getToRevision(); ?>"><span class="monospace"><?php echo substr($deployment->getToRevision(), 0, 7); ?></span></td>
					<td><?php echo $deployment->getComment(); ?></td>
					<td><?php echo $deployment->getUser()->getName(); ?></td>
					<td class="nowrap">
						<img src="/images/icons/<?php echo $deployment->getDeploymentStatus()->getImageName(); ?>" alt="icon" />
						<?php echo $deployment->getDeploymentStatus()->getShortName(); ?>
					</td>
					<td class="icon">
						<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $this->project->getSlug(); ?>/deploy?to=<?php echo $deployment->getFromRevision(); ?>">
							<img src="/images/icons/undo/16x16.png" alt="<?php _e("Roll back"); ?> &raquo;" title="<?php _e("Click to start a roll back to the from revision of this deployment"); ?>" />
						</a>
					</td>
					<td class="icon">
						<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $this->project->getSlug(); ?>/deploy/result/<?php echo $deployment->getId(); ?>">
							<img src="/images/icons/view/16x16.png" alt="<?php _e("View"); ?> &raquo;" title="<?php _e("Click to view this deployment"); ?>" />
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
<?php else: ?>
		<h2 class="last"><?php _e("This project is yet to be deployed."); ?></h2>
<?php endif; ?>
	</div></div>
</div>

