
<?php
	$class_name = "";
	if ($this->element->isRequired()) $class_name .= " required";

	if ($this->element->hasErrors())
	{
		$class_name .= " error";
		$error_message = reset($this->element->getMessages());
	}

?>
<li id="item_<?php echo $this->element->getId(); ?>" class="<?php echo $class_name; ?>">
	<label>
		<span>
			<span title="<?php if ($this->element->hasErrors()) echo $error_message; ?>"></span>
			<?php echo $this->element->getLabel(); ?>
		</span>
	</label>
	<span class="field"><?php
		echo $this->{$this->element->helper}(
			$this->element->getName(),
			$this->element->getValue(),
			$this->element->getAttribs(),
			$this->element->options
		);
	?></span>
	<div class="clear"></div>
</li>
