
<div id="header_border"><div class="content">
	<div class="container">

		<div id="logo">
			<a href="<?php echo $this->baseUrl(); ?>/home" title="GoDeploy - <?php __("Easy Code Deployment"); ?>"><img src="<?php echo $this->baseUrl(); ?>/images/header/godeploy.png" alt="GoDeploy - <?php __("Easy Code Deployment"); ?>" /></a>
			<h2 class="hidden">GoDeploy - <?php __("Easy Code Deployment"); ?></h2>
		</div>

		<?php if($this->show_navigation !== false): ?>
		<div id="menu">
			<?php echo $this->navigation()->menu(); ?>

			<span id="logged_in_status">
			<?php if ($this->logged_in): ?>
				<?php __("Logged in as"); ?> <?php echo Zend_Auth::getInstance()->getIdentity(); ?>
			<?php else: ?>
				<?php __("Not logged in."); ?>
			<?php endif; ?>
			</span>

			<div class="clear"></div>
		</div>
		<?php endif; ?>

		<div class="clear"></div>

	</div>
</div></div>
