<h2><?php echo $this->project->getName(); ?> &ndash; Project Settings</h2>
<?php echo $this->form; ?>

<h2>Servers</h2>
<?php if(is_array($this->servers) && count($this->servers) > 0): $another = "another"; ?>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Hostname</th>
			<th>Type</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->servers as $server): ?>
		<tr>
			<td><?php echo $this->escape($server->getName()); ?></td>
			<td><?php echo $this->escape($server->getHostname()); ?></td>
			<td><?php echo $this->escape($server->getConnectionTypesId()); ?></td>
			<td>Edit | Delete</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
<?php else: $another = "the first"; ?>
<p><strong>There are no servers currently configured for this project!</strong></p>
<?php endif; ?>
<a href="#">Add <?php echo $another; ?> server to this project.</a>