SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_ALL_TABLES';

ALTER TABLE  `users`
  ADD  `date_added` DATETIME NOT NULL ,
  ADD  `date_updated` DATETIME NOT NULL ,
  ADD  `date_disabled` DATETIME NOT NULL ,
  ADD  `admin` BOOL NOT NULL ,
  ADD  `active` BOOL NOT NULL ;

UPDATE `users` SET `active` = '1';

UPDATE `configuration` SET `value` = '5' WHERE `key` = 'db_version';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
