
<div class="content">
	<div class="padding_20"></div>

	<h1><?php _e("Oh dear - something went wrong"); ?>&hellip;</h1>
	<div class="padding_15"></div>

	<div id="form">
		<div class="wrapper w_ededed">
			<div class="content">
				<div class="padding_20"></div>
				<h2><?php echo $this->message; ?></h2>

			<?php if (isset($this->extended_information)): ?>
				<?php echo $this->extended_information; ?>
			<?php endif; ?>

			<?php if (isset($this->exception)): ?>
				<div class="padding_10"></div>
				<div style="background-color: #f0d1d1; padding: 20px; overflow: scroll;">
					<h2><?php _e("Debug Information (Developer Mode)"); ?></h2>
					<h3><?php _e("Exception information"); ?>:</h3>
					<p>
						<b><?php _e("Message"); ?>:</b> <?php echo $this->exception->getMessage() ?>
					</p>

					<h3><?php _e("Stack trace"); ?>:</h3>
					<pre><?php echo $this->exception->getTraceAsString() ?>
					</pre>

					<h3><?php _e("Request Parameters"); ?>:</h3>
					<pre><?php echo var_export($this->request->getParams(), true) ?>
					</pre>
				</div>
			<?php endif; ?>
			</div>
		</div>
	</div>
</div>
