<div class="content">
	<div class="padding_20"></div>

	<h1><?php _e("Change Your Password"); ?></h1>
	<div class="padding_15"></div>

	<div id="form">
		<div class="wrapper w_ededed">
			<div class="content">
				<div class="padding_15"></div>
				<?php if ($this->form->isErrors()) : ?>
					<div id="errors"><div class="content">
						<?php _e("There was a problem with your submission. Please check the fields highlighted below."); ?>
					</div></div>
					<div class="padding_15"></div>
				<?php elseif(isset($this->success)): ?>
					<p><?php _e("Success! Your password was changed."); ?></p>
				<?php endif; ?>
				<?php echo $this->form; ?>
			</div>
		</div>
	</div>
</div>