
<div class="content">
<div class="padding_20"></div>
<h1><?php echo $this->project->getName(); ?> &raquo; <?php _e("Configuration Management"); ?></h1>
<div class="padding_15"></div>

<div class="wrapper w_ededed"><div class="content">
	<div class="padding_15"></div>
	<h2><?php _e("Configuration Editor"); ?></h2>
	<div id="form">
		<form id="configEditor" enctype="application/x-www-form-urlencoded" action="" method="post">
			<input type="hidden" name="id" value="<?php echo $this->config->getId(); ?>" />
			<fieldset>
				<ol>
					<li>
						<label><span><?php _e("Path to file"); ?></span></label>
						<span class="field">
							<input type="text" id="filename" name="filename" value="<?php echo $this->config->getFilename(); ?>" />
							<span class="extras">
								<span class="description">This must be a path relative to the folder in which <?php echo $this->project->getName(); ?> will be deployed, e.g. <span class="monospace">config/db.ini</span></span>
							</span>
						</span>
						<div class="clear"></div>
					</li>
					<li>
						<label><span><?php _e("Content of file to be uploaded"); ?></span></label>
						<textarea name="configContent" id="configContent"><?php echo $this->config->getContent(); ?></textarea>
						<div class="clear"></div>
					</li>
					<li>
						<label><span><?php _e("Upload to servers"); ?></span></label>
						<span class="field" id="configServerCheckboxes">
							<ul>
								<li>
									<input type="checkbox" name="server[]" id="server_all" value="all" checked="checked" />
									<label for="server_all">All servers</label>
									<div class="clear"></div>
								</li>
								<li>
									<input type="checkbox" name="server[]" id="server_first" value="first" />
									<label for="server_first">First server</label>
									<div class="clear"></div>
								</li>
							</ul>
						</span>
						<div class="clear"></div>
					</li>
					<li class="submit">
						<input type="image" name="btnSave" id="btnSave" src="/images/buttons/small/save-changes.png" />
						<span id="linkBack"><a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $this->project->getSlug(); ?>/configs"><?php _e("&hellip;or go back"); ?></a></span>
						<div class="clear"></div>
					</li>
				</ol>
			</fieldset>
		</form>
	</div>
</div></div>

<div class="padding_20"></div>

