
<?php $this->headScript()->appendFile('/js/show-deployment.js'); ?>

<h1><?php echo $project->getDisplayName(); ?> : Deployment #<span id="deploy-id"><?php echo $deployment->getId(); ?></span></h1>

<dl class="dl-horizontal">
    <dt>User:</dt>
        <dd><?php echo $user->getDisplayName(); ?></dd>
    <dt>Date:</dt>
        <dd><?php echo $deployment->getDateAdded('d/m/Y H:i:s'); ?></dd>
    <dt>Previous:</dt>
        <dd><code><?php echo $deployment->getPreviousRevision(); ?></code></dd>
    <dt>Revision:</dt>
        <dd><code id="deploy-rev"><?php echo $deployment->hasResolvedRevision() ? $deployment->getResolvedRevision() : $deployment->getRevision(); ?></code></dd>
    <dt>Comment:</dt>
        <dd><?php echo $deployment->getComment(); ?></dd>
    <dt>Status:</dt>
        <dd id="deploy-status"><?php echo $deployment->getStatus(); ?></dd>
</dl>

<h3>Commit List</h3>
<?php echo $this->commitList($commitList); ?>

<h3>Actions</h3>
<button class="btn btn-success" id="btn-deploy" disabled>Deploy</button>
<button class="btn btn-warning" id="btn-deploy" disabled>Rollback</button>

<div id="deploy-result">
    <h3>Result</h3>
    <pre id="deploy-result-content"><?php echo $log ? $log->getLog() : 'No deployment log'; ?></pre>
</div>
