
<div class="content">
	<div class="padding_20"></div>

	<h1>
		<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $this->project->getSlug(); ?>/settings"><?php echo $this->project->getName(); ?></a> &raquo;
		<?php echo $this->server->getName(); ?>
	</h1>
	<div class="padding_15"></div>

	<div id="form"><div class="wrapper w_ededed"><div class="content">
		<div class="padding_15"></div>

		<h2><?php _e("Server Details"); ?></h2>

	<?php
	if ($this->form->isErrors())
	{
		echo '<div id="errors"><div class="content">';
		if(in_array("FTP_CONNECT_ERROR", $this->form->getErrorMessages()))
		{
			_e("There was a problem connecting to the FTP server with the information you provided.");
			echo "<br /><br />";
			_e("Please check the username and password, and ensure the user has permissions to create and delete files on the FTP server.");

			if(isset($this->ftpMessage) && $this->ftpMessage != '')
			{
				echo "<br /><br />";
				_e("More information that might be useful: ");
				echo "<span style=\"font-weight: normal\">{$this->ftpMessage}</span>";
			}
		}
		else
		{
			_e("There was a problem with your submission. Please check the fields highlighted below.");
		}
		echo '</div></div><div class="padding_15"></div>';
	}

	echo $this->form;
	?>

	</div></div></div>
</div>
