
<div class="content">
	<div class="padding_20"></div>

	<h1>
		<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $this->project->getSlug(); ?>/settings"><?php echo $this->project->getName(); ?></a> &raquo;
		<?php echo $this->server->getName(); ?>
	</h1>
	<div class="padding_15"></div>

	<div id="form"><div class="wrapper w_ededed"><div class="content">
		<div class="padding_15"></div>

		<h2>Project Settings</h2>

	<?php if ($this->form->isErrors()) : ?>
		<div id="errors"><div class="content">
			There was a problem with your submission. Please check the fields highlighted below.
		</div></div>
		<div class="padding_15"></div>
	<?php endif; ?>
		<?php echo $this->form; ?>

	</div></div></div>
</div>
