
<div class="content">
	<div class="padding_20"></div>

	<h1>Welcome <?php if (count($this->projects) > 0) echo "back "; ?> to Godeploy</h1>
	<div class="padding_15"></div>

	<div id="projects"><div class="wrapper w_ededed"><div class="content">
		<div class="padding_15"></div>

	<?php if (is_array($this->projects) && count($this->projects) > 0): ?>

		<h2>We've missed you - how have you been?</h2>
		<p>Now you're back, here's your list of current projects - you can deploy or update any of them, or add a whole new one.</p>
		<div class="padding_5"></div>

		<table>
			<thead>
				<tr>
					<th><?php _e("Project name"); ?></th>
					<th><?php _e("Last deployed"); ?></th>
					<th colspan="2"><?php _e("Deployments"); ?></th>
					<th class="empty">&nbsp;</th>
				</tr>
			</thead>
			<tbody>
			<?php
				foreach ($this->projects as $project)
				{
					$last_deployment = $project->getLastDeployment();
					$num_deployments = $project->getNumDeployments();
			?>
				<tr>
					<td><?php echo $this->escape($project->getName()); ?></td>
					<td>
					<?php if ($last_deployment instanceof GD_Model_Deployment): ?>
						<?php echo $last_deployment->getWhen(); ?>
					<?php else: ?>
						<strong>This project is yet to be deployed.</strong>
					<?php endif; ?>
					</td>
					<td>
					<?php if ($num_deployments > 0): ?>
						<p>Deployed <?php echo ($num_deployments > 1) ? $num_deployments . " times" : "once"; ?></p>
						<p><a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $project->getSlug(); ?>/history" class="view_icon">View history</a></p>
					<?php else: ?>
						0 deployments
					<?php endif; ?>
					</td>
					<td class="icon">
						<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $project->getSlug(); ?>/deploy">
							<img src="/images/buttons/small/deploy-project.png" alt="Deploy project &raquo;" />
						</a>
					</td>
					<td class="icon">
						<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $project->getSlug(); ?>/settings">
							<img src="/images/icons/edit/16x16.png" alt="Edit &raquo;" />
						</a>
					</td>
				</tr>
			<?php
				}
			?>
			</tbody>
		</table>
		<div class="padding_15"></div>

		<p class="last"><a href="<?php echo $this->baseUrl(); ?>/project/new/settings" class="add_icon"><?php _e("Add another project"); ?></a></p>

	<?php else: ?>

		<h2>You haven't set any projects up to deploy yet.</h2>
		<p class="last"><a href="<?php echo $this->baseUrl(); ?>/project/new/settings" class="add_icon"><?php _e("Add the first project"); ?></a></p>

	<?php endif; ?>

	</div></div></div>

</div>
