
<?php if(is_array($this->projects) && count($this->projects) > 0): $another = true; ?>
<ul id="projects">
<?php foreach($this->projects as $project): ?>
	<li>
		<a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $project->getSlug(); ?>/deploy">
			<img src="<?php echo $this->baseUrl(); ?>/images/buttons/medium/deploy.png" alt="Deploy" title="Deploy this project now" />
		</a>
		<h4><?php echo $project->getName(); ?></h4>
		<ul class="links">
			<li><a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $project->getSlug(); ?>/history"><?php _e("Deployments"); ?></a></li>
			<li><a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $project->getSlug(); ?>/settings"><?php _e("Settings"); ?></a></li>
			<li><a href="<?php echo $this->baseUrl(); ?>/project/<?php echo $project->getSlug(); ?>/settings/confirm-delete"><?php _e("Delete"); ?></a></li>
		</ul>
		<div class="clear"></div>
	</li>
<?php endforeach; ?>
</ul>
<?php else: $another = false; ?>
<?php _e("No projects set up yet."); ?>
<?php endif; ?>
<p class="align_center"><a href="<?php echo $this->baseUrl(); ?>/project/new/settings" class="add_icon"><?php
	if($another)
		_e("Add another project");
	else
		_e("Add the first project");
?></a></p>
