<?php echo $this->doctype() . "\n"; ?>
<html>
<head>
<?php echo $this->headTitle() . "\n"; ?>

<!-- Javascript -->
<?php echo $this->headScript() . "\n"; ?>

<!-- Stylesheets -->
<?php echo $this->headLink() . "\n"; ?>

<!-- Shortcut icon -->
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

<!-- Meta tags -->
<?php echo $this->headMeta() . "\n"; ?>
</head>
<body>

<div id="container">
	<div id="header"><?php echo $this->render('header.phtml'); ?></div>
	<hr />
	<div id="main"><div class="container">
		<?php echo $this->layout()->content; ?>
	</div></div>
	<hr />
	<div id="footer"><?php echo $this->render('footer.phtml'); ?></div>
</div>

</body>
</html>